import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>Foodie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="test">            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Placeat laudantium aut minima doloribus, tempore voluptatem. Expedita sint nam maxime facere facilis asperiores accusamus libero ab, nesciunt ipsam. Nulla, neque veritatis.</h1>
    </>
  )
}
